# Generated by Django 2.2.2 on 2019-06-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=3, verbose_name='1st question')),
                ('question2', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=3, verbose_name='2nd question')),
                ('question3', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=3, verbose_name='3rd question')),
                ('question4', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=3, verbose_name='4th question')),
                ('question5', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=3, verbose_name='5th question')),
                ('gm_name', models.CharField(choices=[('ab@ab.com', 'ab@ab.com'), ('bc@bc.com', 'bc@bc.com'), ('akash.kumar5@oyorooms.com', 'akash.kumar5@oyorooms.com'), ('abc@abc.com', 'abc@abc.com'), ('akashkumarqoou1997@gmail.com', 'akashkumarqoou1997@gmail.com')], default='Akash', max_length=50, verbose_name='GM Name')),
                ('product_type', models.CharField(choices=[('All', 'all'), ('TownHouse', 'townhouse'), ('Collection O', 'collection_o'), ('Flagship', 'flagship'), ('Silver Key', 'silver_key')], default='TownHouse', max_length=30, verbose_name='OYO Product')),
                ('assigned_by', models.CharField(default='Akash', max_length=50)),
                ('editable', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='Yes', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='Please type Question', max_length=2500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('All', 'all'), ('TownHouse', 'townhouse'), ('Collection O', 'collection_o'), ('Flagship', 'flagship'), ('Silver Key', 'silver_key')], default='All', max_length=50)),
                ('answer_choice', models.CharField(default='0', max_length=5)),
                ('task_name', models.CharField(default='Task Heading', max_length=500)),
                ('task_description', models.CharField(default='Task Description', max_length=1000)),
                ('task_deadline_expected', models.IntegerField(default=2, verbose_name='Number of Days for task completion')),
                ('priority', models.PositiveIntegerField(default=5, verbose_name='Priority as a number between 1 to 5')),
                ('question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Questions')),
            ],
        ),
    ]
