# Generated by Django 2.2.2 on 2019-06-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190622_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardanswer',
            name='task_name',
        ),
    ]
