# Generated by Django 2.2.2 on 2019-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_standardanswer_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestions',
            name='gm_name',
            field=models.CharField(choices=[('12345', '12345')], default='12345', max_length=50, verbose_name='GM Name'),
        ),
    ]
