# Generated by Django 2.2.2 on 2019-06-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190623_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestions',
            name='assigned_by',
            field=models.CharField(choices=[('Akash', 'Akash')], default='Akash', max_length=50, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='formquestions',
            name='gm_name',
            field=models.CharField(choices=[('12345', '12345')], default='12345', max_length=50, verbose_name='GM Name'),
        ),
    ]
