# Generated by Django 2.2.2 on 2019-06-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190623_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardanswer',
            name='question',
            field=models.CharField(default='Please type Question', max_length=2500),
        ),
    ]
