# Generated by Django 2.2.2 on 2019-06-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_standardanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardanswer',
            name='answer_choice',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='Yes', max_length=3),
        ),
    ]
