# Generated by Django 2.2.2 on 2019-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20190624_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestions',
            name='editable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='formquestions',
            name='product_type',
            field=models.CharField(choices=[('all', 'All'), ('townhouse', 'TownHouse'), ('collection_o', 'Collection O'), ('flagship', 'Flagship'), ('silver_key', 'Silver Key')], default='TownHouse', max_length=30, verbose_name='OYO Product'),
        ),
        migrations.AlterField(
            model_name='formquestions',
            name='question1',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='1st question'),
        ),
        migrations.AlterField(
            model_name='formquestions',
            name='question2',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='2nd question'),
        ),
        migrations.AlterField(
            model_name='formquestions',
            name='question3',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='3rd question'),
        ),
        migrations.AlterField(
            model_name='formquestions',
            name='question4',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='4th question'),
        ),
        migrations.AlterField(
            model_name='formquestions',
            name='question5',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='5th question'),
        ),
        migrations.AlterField(
            model_name='standardanswer',
            name='answer_choice',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='standardanswer',
            name='property_type',
            field=models.CharField(choices=[('all', 'All'), ('townhouse', 'TownHouse'), ('collection_o', 'Collection O'), ('flagship', 'Flagship'), ('silver_key', 'Silver Key')], default='all', max_length=50),
        ),
    ]
